name = "job-visualizer"
main = "backend/worker.js"
compatibility_date = "2024-09-19"

[vars]
ENVIRONMENT = "production"
GOOGLE_REDIRECT_URI = "https://mapmyjob.in/api/auth/callback"
GOOGLE_CLIENT_ID = "614597180918-81b3rlfuesd82bkdoltga92sb9vplfr5.apps.googleusercontent.com"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "ae27dac64a534dc485511d6911cae2fd"

[[d1_databases]]
binding = "DB"
database_name = "jobs-visualizer-db"
database_id = "3f8b6152-4315-4ce1-a449-b2014c740bf5"

