import unittest
import os
from data_acquisition.geo_config import (
    CITY_SYNONYMS,
    match_target_city,
    get_mock_jobs,
)
from data_acquisition.heal_geocodes import clean_snippet_to_address
from data_acquisition.job_validator import JobValidator


class TestIndiaRemediation(unittest.TestCase):
    def test_city_synonyms_expanded(self):
        """Verify that major India tech hubs are present in CITY_SYNONYMS."""
        for city in ["pune", "chennai", "gurugram", "gurgaon", "noida", "delhi", "bengaluru", "mumbai", "hyderabad", "india", "in"]:
            self.assertIn(city, CITY_SYNONYMS)

    def test_match_target_city_india_wide(self):
        """Verify nationwide and city-specific matching in match_target_city."""
        self.assertTrue(match_target_city("HSR Layout, Bengaluru, Karnataka", "Bengaluru"))
        self.assertTrue(match_target_city("HSR Layout, Bengaluru", "Bangalore"))
        self.assertTrue(match_target_city("Kalyani Nagar, Pune, MH", "Pune"))
        self.assertTrue(match_target_city("Cyber City, Gurugram, HR", "Gurgaon"))
        self.assertTrue(match_target_city("Bengaluru, India", "india"))
        self.assertTrue(match_target_city("Pune, Maharashtra", "in"))

    def test_parameterized_snippet_cleaning(self):
        """Verify clean_snippet_to_address uses target_city parameter correctly."""
        addr_pune = clean_snippet_to_address("Headquarters at Kalyani Nagar, Pune", target_city="Pune")
        self.assertIn("Pune", addr_pune)
        addr_chennai = clean_snippet_to_address("Located in T Nagar, Chennai", target_city="Chennai")
        self.assertIn("Chennai", addr_chennai)

    def test_mock_fallback_generation(self):
        """Verify deterministic mock jobs generated by get_mock_jobs."""
        jobs = get_mock_jobs("TestScraper", "AI Engineer", target_city="Pune", company_name="Pune Tech")
        self.assertEqual(len(jobs), 1)
        self.assertEqual(jobs[0]["company_name"], "Pune Tech")
        self.assertEqual(jobs[0]["location"], "Pune")
        self.assertEqual(jobs[0]["source"], "TestScraper")

    def test_job_validator_mock_fallback(self):
        """Verify JobValidator accepts mock URLs when MOCK_SCRAPER_FALLBACK is true."""
        os.environ["MOCK_SCRAPER_FALLBACK"] = "true"
        validator = JobValidator(None)
        active, reason = validator._check_job_active("https://www.google.com/jobs/mock-test-1")
        self.assertTrue(active)
        self.assertIn("Active", reason)


if __name__ == "__main__":
    unittest.main()
